import Navbar from "@/components/Navbar";
import { NextUIProvider } from "@nextui-org/system";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { BackgroundCellCore } from "@/components/ui/BackgroundRippleEffect";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} dark`}>
        <NextUIProvider>
          <section className="relative z-10 flex h-screen items-center justify-center overflow-hidden bg-slate-950">
            <BackgroundCellCore />
            <Navbar />
            {children}
          </section>
        </NextUIProvider>
      </body>
    </html>
  );
}
